package controllers;

import javax.mail.*;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import java.io.UnsupportedEncodingException;
import java.util.Date;
import java.util.Properties;

public class SendMail {

    public void sendCode(String code, String email) throws MessagingException, UnsupportedEncodingException {
        final String fromEmail = "hotrofuda@gmail.com";
        // Mat khai email cua ban
        final String password = "tdnhjwnggkyakjec";
        // dia chi email nguoi nhan
        final String toEmail = email;

        final String subject = "[FUDA Bus Lines] Verify your new account";
        final String body = "<!doctype html>\n"
                + "<html>\n"
                + "\n"
                + "<head>\n"
                + "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n"
                + "  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n"
                + "  <style>\n"
                + "    img {\n"
                + "      border: none;\n"
                + "      -ms-interpolation-mode: bicubic;\n"
                + "      max-width: 100%;\n"
                + "    }\n"
                + "\n"
                + "    body {\n"
                + "      background-color: #8c8c8c;\n"
                + "      font-family: sans-serif;\n"
                + "      -webkit-font-smoothing: antialiased;\n"
                + "      font-size: 14px;\n"
                + "      line-height: 1.4;\n"
                + "      margin: 0;\n"
                + "      padding: 0;\n"
                + "    }\n"
                + "\n"
                + "    table {\n"
                + "      border-collapse: separate;\n"
                + "      mso-table-lspace: 0pt;\n"
                + "      mso-table-rspace: 0pt;\n"
                + "      width: 100%;\n"
                + "    }\n"
                + "\n"
                + "    table td {\n"
                + "      font-family: sans-serif;\n"
                + "      font-size: 14px;\n"
                + "      vertical-align: top;\n"
                + "    }\n"
                + "\n"
                + "    /* -------------------------------------\n"
                + "          BODY & CONTAINER\n"
                + "      ------------------------------------- */\n"
                + "\n"
                + "    .body {\n"
                + "      background-color: #8c8c8c;\n"
                + "      width: 100%;\n"
                + "    }\n"
                + "\n"
                + "    /* Set a max-width, and make it display as block so it will automatically stretch to that width, but will also shrink down on a phone or something */\n"
                + "    .container {\n"
                + "      display: block;\n"
                + "      margin: 0 auto !important;\n"
                + "      /* makes it centered */\n"
                + "      max-width: 580px;\n"
                + "      padding: 10px;\n"
                + "      width: 580px;\n"
                + "    }\n"
                + "\n"
                + "    /* This should also be a block element, so that it will fill 100% of the .container */\n"
                + "    .content {\n"
                + "      box-sizing: border-box;\n"
                + "      display: block;\n"
                + "      margin: 0 auto;\n"
                + "      max-width: 580px;\n"
                + "      padding: 10px;\n"
                + "    }\n"
                + "\n"
                + "    /* -------------------------------------\n"
                + "          HEADER, FOOTER, MAIN\n"
                + "      ------------------------------------- */\n"
                + "    .main {\n"
                + "      background: #ffffff;\n"
                + "      border-radius: 3px;\n"
                + "      width: 100%;\n"
                + "    }\n"
                + "\n"
                + "    .wrapper {\n"
                + "      box-sizing: border-box;\n"
                + "      padding: 20px;\n"
                + "    }\n"
                + "\n"
                + "    .content-block {\n"
                + "      padding-bottom: 10px;\n"
                + "      padding-top: 10px;\n"
                + "    }\n"
                + "\n"
                + "    .footer {\n"
                + "      clear: both;\n"
                + "      margin-top: 10px;\n"
                + "      text-align: center;\n"
                + "      width: 100%;\n"
                + "    }\n"
                + "\n"
                + "    .footer td,\n"
                + "    .footer p,\n"
                + "    .footer span,\n"
                + "    .footer a {\n"
                + "      color: #ffffff;\n"
                + "      font-size: 12px;\n"
                + "      text-align: center;\n"
                + "    }\n"
                + "\n"
                + "    /* -------------------------------------\n"
                + "          TYPOGRAPHY\n"
                + "      ------------------------------------- */\n"
                + "    h1,\n"
                + "    h2,\n"
                + "    h3,\n"
                + "    h4 {\n"
                + "      color: #000000;\n"
                + "      font-family: sans-serif;\n"
                + "      font-weight: 400;\n"
                + "      line-height: 1.4;\n"
                + "      margin: 0;\n"
                + "      margin-bottom: 30px;\n"
                + "    }\n"
                + "\n"
                + "    h1 {\n"
                + "      font-size: 35px;\n"
                + "      font-weight: 300;\n"
                + "      text-align: center;\n"
                + "      text-transform: capitalize;\n"
                + "    }\n"
                + "\n"
                + "    p,\n"
                + "    ul,\n"
                + "    ol {\n"
                + "      font-family: sans-serif;\n"
                + "      font-size: 14px;\n"
                + "      font-weight: normal;\n"
                + "      margin: 0;\n"
                + "      margin-bottom: 15px;\n"
                + "    }\n"
                + "\n"
                + "    p li,\n"
                + "    ul li,\n"
                + "    ol li {\n"
                + "      list-style-position: inside;\n"
                + "      margin-left: 5px;\n"
                + "    }\n"
                + "\n"
                + "    a {\n"
                + "      color: #3498db;\n"
                + "      text-decoration: underline;\n"
                + "    }\n"
                + "\n"
                + "    /* -------------------------------------\n"
                + "          BUTTONS\n"
                + "      ------------------------------------- */\n"
                + "    .btn {\n"
                + "      box-sizing: border-box;\n"
                + "      width: 100%;\n"
                + "    }\n"
                + "\n"
                + "    .btn>tbody>tr>td {\n"
                + "      padding-bottom: 15px;\n"
                + "    }\n"
                + "\n"
                + "    .btn table {\n"
                + "      width: auto;\n"
                + "    }\n"
                + "\n"
                + "    .btn table td {\n"
                + "      background-color: #ffffff;\n"
                + "      border-radius: 5px;\n"
                + "      text-align: center;\n"
                + "    }\n"
                + "\n"
                + "    .btn a {\n"
                + "      background-color: #ffffff;\n"
                + "      border: solid 1px #3498db;\n"
                + "      border-radius: 5px;\n"
                + "      box-sizing: border-box;\n"
                + "      color: #3498db;\n"
                + "      cursor: pointer;\n"
                + "      display: inline-block;\n"
                + "      font-size: 14px;\n"
                + "      font-weight: bold;\n"
                + "      margin: 0;\n"
                + "      padding: 12px 25px;\n"
                + "      text-decoration: none;\n"
                + "      text-transform: capitalize;\n"
                + "    }\n"
                + "\n"
                + "    .btn-primary table td {\n"
                + "      background-color: #3498db;\n"
                + "    }\n"
                + "\n"
                + "    .btn-primary a {\n"
                + "      background-color: #3498db;\n"
                + "      border-color: #3498db;\n"
                + "      color: #ffffff;\n"
                + "    }\n"
                + "\n"
                + "    /* -------------------------------------\n"
                + "          OTHER STYLES THAT MIGHT BE USEFUL\n"
                + "      ------------------------------------- */\n"
                + "    .last {\n"
                + "      margin-bottom: 0;\n"
                + "    }\n"
                + "\n"
                + "    .first {\n"
                + "      margin-top: 0;\n"
                + "    }\n"
                + "\n"
                + "    .align-center {\n"
                + "      text-align: center;\n"
                + "    }\n"
                + "\n"
                + "    .align-right {\n"
                + "      text-align: right;\n"
                + "    }\n"
                + "\n"
                + "    .align-left {\n"
                + "      text-align: left;\n"
                + "    }\n"
                + "\n"
                + "    .clear {\n"
                + "      clear: both;\n"
                + "    }\n"
                + "\n"
                + "    .mt0 {\n"
                + "      margin-top: 0;\n"
                + "    }\n"
                + "\n"
                + "    .mb0 {\n"
                + "      margin-bottom: 0;\n"
                + "    }\n"
                + "\n"
                + "    .preheader {\n"
                + "      color: transparent;\n"
                + "      display: none;\n"
                + "      height: 0;\n"
                + "      max-height: 0;\n"
                + "      max-width: 0;\n"
                + "      opacity: 0;\n"
                + "      overflow: hidden;\n"
                + "      mso-hide: all;\n"
                + "      visibility: hidden;\n"
                + "      width: 0;\n"
                + "    }\n"
                + "\n"
                + "    .powered-by a {\n"
                + "      text-decoration: none;\n"
                + "    }\n"
                + "\n"
                + "    hr {\n"
                + "      border: 0;\n"
                + "      border-bottom: 1px solid #f6f6f6;\n"
                + "      margin: 20px 0;\n"
                + "    }\n"
                + "\n"
                + "    /* -------------------------------------\n"
                + "          RESPONSIVE AND MOBILE FRIENDLY STYLES\n"
                + "      ------------------------------------- */\n"
                + "    @media only screen and (max-width: 620px) {\n"
                + "      table.body h1 {\n"
                + "        font-size: 28px !important;\n"
                + "        margin-bottom: 10px !important;\n"
                + "      }\n"
                + "\n"
                + "      table.body p,\n"
                + "      table.body ul,\n"
                + "      table.body ol,\n"
                + "      table.body td,\n"
                + "      table.body span,\n"
                + "      table.body a {\n"
                + "        font-size: 16px !important;\n"
                + "      }\n"
                + "\n"
                + "      table.body .wrapper,\n"
                + "      table.body .article {\n"
                + "        padding: 10px !important;\n"
                + "      }\n"
                + "\n"
                + "      table.body .content {\n"
                + "        padding: 0 !important;\n"
                + "      }\n"
                + "\n"
                + "      table.body .container {\n"
                + "        padding: 0 !important;\n"
                + "        width: 100% !important;\n"
                + "      }\n"
                + "\n"
                + "      table.body .main {\n"
                + "        border-left-width: 0 !important;\n"
                + "        border-radius: 0 !important;\n"
                + "        border-right-width: 0 !important;\n"
                + "      }\n"
                + "\n"
                + "      table.body .btn table {\n"
                + "        width: 100% !important;\n"
                + "      }\n"
                + "\n"
                + "      table.body .btn a {\n"
                + "        width: 100% !important;\n"
                + "      }\n"
                + "\n"
                + "      table.body .img-responsive {\n"
                + "        height: auto !important;\n"
                + "        max-width: 100% !important;\n"
                + "        width: auto !important;\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    /* -------------------------------------\n"
                + "          PRESERVE THESE STYLES IN THE HEAD\n"
                + "      ------------------------------------- */\n"
                + "    @media all {\n"
                + "      .ExternalClass {\n"
                + "        width: 100%;\n"
                + "      }\n"
                + "\n"
                + "      .ExternalClass,\n"
                + "      .ExternalClass p,\n"
                + "      .ExternalClass span,\n"
                + "      .ExternalClass font,\n"
                + "      .ExternalClass td,\n"
                + "      .ExternalClass div {\n"
                + "        line-height: 100%;\n"
                + "      }\n"
                + "\n"
                + "      .apple-link a {\n"
                + "        color: inherit !important;\n"
                + "        font-family: inherit !important;\n"
                + "        font-size: inherit !important;\n"
                + "        font-weight: inherit !important;\n"
                + "        line-height: inherit !important;\n"
                + "        text-decoration: none !important;\n"
                + "      }\n"
                + "\n"
                + "      #MessageViewBody a {\n"
                + "        color: inherit;\n"
                + "        text-decoration: none;\n"
                + "        font-size: inherit;\n"
                + "        font-family: inherit;\n"
                + "        font-weight: inherit;\n"
                + "        line-height: inherit;\n"
                + "      }\n"
                + "\n"
                + "      .btn-primary table td:hover {\n"
                + "        background-color: #34495e !important;\n"
                + "      }\n"
                + "\n"
                + "      .btn-primary a:hover {\n"
                + "        background-color: #34495e !important;\n"
                + "        border-color: #34495e !important;\n"
                + "      }\n"
                + "    }\n"
                + "  </style>\n"
                + "</head>\n"
                + "\n"
                + "<body>\n"
                + "  <span class=\"preheader\">FUDA Verification Code</span>\n"
                + "  <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"body\">\n"
                + "    <tr>\n"
                + "      <td>&nbsp;</td>\n"
                + "      <td class=\"container\">\n"
                + "        <div class=\"content\">\n"
                + "\n"
                + "          <!-- START CENTERED WHITE CONTAINER -->\n"
                + "          <table role=\"presentation\" class=\"main\">\n"
                + "\n"
                + "            <!-- START MAIN CONTENT AREA -->\n"
                + "            <tr>\n"
                + "              <td class=\"wrapper\">\n"
                + "                <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
                + "                  <tr>\n"
                + "                    <td>\n"
                + "                      <p>Hi " + email + " ! </p>\n"
                + "                      <p>Here's your account launch code.</p>\n"
                + "                      <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"btn btn-succesed\">\n"
                + "                        <tbody>\n"
                + "                          <tr>\n"
                + "                            <td align=\"left\">\n"
                + "                              <table role=\"\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
                + "                                <tbody>\n"
                + "                                  <tr>\n"
                + "                                    <span\n"
                + "                                      style=\"box-sizing:border-box;color:#24292e!important;display:inline-block;background-color:#dedede;border-radius:6px;padding:2px 6px;font:300 48px &quot;SFMono-Regular&quot;,Consolas,&quot;Liberation Mono&quot;,Menlo,monospace\">\n"
                + "                                      " + code + "\n"
                + "                                    </span>\n"
                + "                                  </tr>\n"
                + "                                </tbody>\n"
                + "                              </table>\n"
                + "                            </td>\n"
                + "                          </tr>\n"
                + "                        </tbody>\n"
                + "                      </table>\n"
                + "                      <p>Once completed, you can start using all of FUDA's features to explore, search bus, booking ticket.</p>\n"
                + "                      <p>Good luck! Hope it works.</p>\n"
                + "                    </td>\n"
                + "                  </tr>\n"
                + "                </table>\n"
                + "              </td>\n"
                + "            </tr>\n"
                + "\n"
                + "            <!-- END MAIN CONTENT AREA -->\n"
                + "\n"
                + "\n"
                + "          </table>\n"
                + "          <!-- END CENTERED WHITE CONTAINER -->\n"
                + "\n"
                + "          <!-- START FOOTER -->\n"
                + "          <div class=\"footer\">\n"
                + "            <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
                + "              <tr>\n"
                + "                <td class=\"content-block\">\n"
                + "                  <a><img width=\"520px\" height=\"250px\" src=\"https://i.ibb.co/RbzXDGH/346163504-269689148792233-5682024559632564645-n.png\" alt=\"346163504-269689148792233-5682024559632564645-n\" border=\"0\"></a>\n"
                + "                  <span class=\"apple-link\">Company FUDA Inc, Urban area FPT City, Ngu Hanh Son, Da Nang</span>\n"
                + "                  <br> SUPPORT: <a href=\"https://mail.google.com/mail/u/0/#inbox\">hotrofuda@gmail.com</a>.\n"
                + "                </td>\n"
                + "              </tr>\n"
                + "              <tr>\n"
                + "                <td class=\"content-block powered-by\">\n"
                + "                  Powered by <a href= \"https://www.facebook.com/huygvr\">HUYTRONGLEE</a>.\n"
                + "                </td>\n"
                + "              </tr>\n"
                + "            </table>\n"
                + "          </div>\n"
                + "          <!-- END FOOTER -->\n"
                + "\n"
                + "        </div>\n"
                + "      </td>\n"
                + "      <td>&nbsp;</td>\n"
                + "    </tr>\n"
                + "  </table>\n"
                + "</body>\n"
                + "\n"
                + "</html>";

        Properties props = new Properties();
        props.put("mail.smtp.host", "smtp.gmail.com"); //SMTP Host
        props.put("mail.smtp.port", "587"); //TLS Port
        props.put("mail.smtp.auth", "true"); //enable authentication
        props.put("mail.smtp.starttls.enable", "true"); //enable STARTTLS

        Authenticator auth = new Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(fromEmail, password);
            }
        };
        Session session = Session.getInstance(props, auth);

        MimeMessage msg = new MimeMessage(session);
        //set message headers
        msg.addHeader("Content-type", "text/HTML; charset=UTF-8");
        msg.addHeader("format", "flowed");
        msg.addHeader("Content-Transfer-Encoding", "8bit");

        msg.setFrom(new InternetAddress(fromEmail, "Fuda Support"));

        msg.setReplyTo(InternetAddress.parse(fromEmail, false));

        msg.setSubject(subject, "UTF-8");

        msg.setContent(body, "text/html; charset=utf-8");

        msg.setSentDate(new Date());

        msg.setRecipients(Message.RecipientType.TO, InternetAddress.parse(toEmail, false));
        Transport.send(msg);
        System.out.println("Gui mail thanh cong");
    }

    public void resetPassword(String code, String email) throws MessagingException, UnsupportedEncodingException {
        final String fromEmail = "hotrofuda@gmail.com";
        // Mat khai email cua ban
        final String password = "tdnhjwnggkyakjec";
        // dia chi email nguoi nhan
        final String toEmail = email;

        final String subject = "[FUDA Bus Lines] Reset Your Password";
        final String body = "<!doctype html>\n"
                + "<html>\n"
                + "\n"
                + "<head>\n"
                + "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n"
                + "  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n"
                + "  <style>\n"
                + "    img {\n"
                + "      border: none;\n"
                + "      -ms-interpolation-mode: bicubic;\n"
                + "      max-width: 100%;\n"
                + "    }\n"
                + "\n"
                + "    body {\n"
                + "      background-color: #8c8c8c;\n"
                + "      font-family: sans-serif;\n"
                + "      -webkit-font-smoothing: antialiased;\n"
                + "      font-size: 14px;\n"
                + "      line-height: 1.4;\n"
                + "      margin: 0;\n"
                + "      padding: 0;\n"
                + "    }\n"
                + "\n"
                + "    table {\n"
                + "      border-collapse: separate;\n"
                + "      mso-table-lspace: 0pt;\n"
                + "      mso-table-rspace: 0pt;\n"
                + "      width: 100%;\n"
                + "    }\n"
                + "\n"
                + "    table td {\n"
                + "      font-family: sans-serif;\n"
                + "      font-size: 14px;\n"
                + "      vertical-align: top;\n"
                + "    }\n"
                + "\n"
                + "    /* -------------------------------------\n"
                + "          BODY & CONTAINER\n"
                + "      ------------------------------------- */\n"
                + "\n"
                + "    .body {\n"
                + "      background-color: #8c8c8c;\n"
                + "      width: 100%;\n"
                + "    }\n"
                + "\n"
                + "    /* Set a max-width, and make it display as block so it will automatically stretch to that width, but will also shrink down on a phone or something */\n"
                + "    .container {\n"
                + "      display: block;\n"
                + "      margin: 0 auto !important;\n"
                + "      /* makes it centered */\n"
                + "      max-width: 580px;\n"
                + "      padding: 10px;\n"
                + "      width: 580px;\n"
                + "    }\n"
                + "\n"
                + "    /* This should also be a block element, so that it will fill 100% of the .container */\n"
                + "    .content {\n"
                + "      box-sizing: border-box;\n"
                + "      display: block;\n"
                + "      margin: 0 auto;\n"
                + "      max-width: 580px;\n"
                + "      padding: 10px;\n"
                + "    }\n"
                + "\n"
                + "    /* -------------------------------------\n"
                + "          HEADER, FOOTER, MAIN\n"
                + "      ------------------------------------- */\n"
                + "    .main {\n"
                + "      background: #ffffff;\n"
                + "      border-radius: 3px;\n"
                + "      width: 100%;\n"
                + "    }\n"
                + "\n"
                + "    .wrapper {\n"
                + "      box-sizing: border-box;\n"
                + "      padding: 20px;\n"
                + "    }\n"
                + "\n"
                + "    .content-block {\n"
                + "      padding-bottom: 10px;\n"
                + "      padding-top: 10px;\n"
                + "    }\n"
                + "\n"
                + "    .footer {\n"
                + "      clear: both;\n"
                + "      margin-top: 10px;\n"
                + "      text-align: center;\n"
                + "      width: 100%;\n"
                + "    }\n"
                + "\n"
                + "    .footer td,\n"
                + "    .footer p,\n"
                + "    .footer span,\n"
                + "    .footer a {\n"
                + "      color: #ffffff;\n"
                + "      font-size: 12px;\n"
                + "      text-align: center;\n"
                + "    }\n"
                + "\n"
                + "    /* -------------------------------------\n"
                + "          TYPOGRAPHY\n"
                + "      ------------------------------------- */\n"
                + "    h1,\n"
                + "    h2,\n"
                + "    h3,\n"
                + "    h4 {\n"
                + "      color: #000000;\n"
                + "      font-family: sans-serif;\n"
                + "      font-weight: 400;\n"
                + "      line-height: 1.4;\n"
                + "      margin: 0;\n"
                + "      margin-bottom: 30px;\n"
                + "    }\n"
                + "\n"
                + "    h1 {\n"
                + "      font-size: 35px;\n"
                + "      font-weight: 300;\n"
                + "      text-align: center;\n"
                + "      text-transform: capitalize;\n"
                + "    }\n"
                + "\n"
                + "    p,\n"
                + "    ul,\n"
                + "    ol {\n"
                + "      font-family: sans-serif;\n"
                + "      font-size: 14px;\n"
                + "      font-weight: normal;\n"
                + "      margin: 0;\n"
                + "      margin-bottom: 15px;\n"
                + "    }\n"
                + "\n"
                + "    p li,\n"
                + "    ul li,\n"
                + "    ol li {\n"
                + "      list-style-position: inside;\n"
                + "      margin-left: 5px;\n"
                + "    }\n"
                + "\n"
                + "    a {\n"
                + "      color: #3498db;\n"
                + "      text-decoration: underline;\n"
                + "    }\n"
                + "\n"
                + "    /* -------------------------------------\n"
                + "          BUTTONS\n"
                + "      ------------------------------------- */\n"
                + "    .btn {\n"
                + "      box-sizing: border-box;\n"
                + "      width: 100%;\n"
                + "    }\n"
                + "\n"
                + "    .btn>tbody>tr>td {\n"
                + "      padding-bottom: 15px;\n"
                + "    }\n"
                + "\n"
                + "    .btn table {\n"
                + "      width: auto;\n"
                + "    }\n"
                + "\n"
                + "    .btn table td {\n"
                + "      background-color: #ffffff;\n"
                + "      border-radius: 5px;\n"
                + "      text-align: center;\n"
                + "    }\n"
                + "\n"
                + "    .btn a {\n"
                + "      background-color: #ffffff;\n"
                + "      border: solid 1px #3498db;\n"
                + "      border-radius: 5px;\n"
                + "      box-sizing: border-box;\n"
                + "      color: #3498db;\n"
                + "      cursor: pointer;\n"
                + "      display: inline-block;\n"
                + "      font-size: 14px;\n"
                + "      font-weight: bold;\n"
                + "      margin: 0;\n"
                + "      padding: 12px 25px;\n"
                + "      text-decoration: none;\n"
                + "      text-transform: capitalize;\n"
                + "    }\n"
                + "\n"
                + "    .btn-primary table td {\n"
                + "      background-color: #3498db;\n"
                + "    }\n"
                + "\n"
                + "    .btn-primary a {\n"
                + "      background-color: #3498db;\n"
                + "      border-color: #3498db;\n"
                + "      color: #ffffff;\n"
                + "    }\n"
                + "\n"
                + "    /* -------------------------------------\n"
                + "          OTHER STYLES THAT MIGHT BE USEFUL\n"
                + "      ------------------------------------- */\n"
                + "    .last {\n"
                + "      margin-bottom: 0;\n"
                + "    }\n"
                + "\n"
                + "    .first {\n"
                + "      margin-top: 0;\n"
                + "    }\n"
                + "\n"
                + "    .align-center {\n"
                + "      text-align: center;\n"
                + "    }\n"
                + "\n"
                + "    .align-right {\n"
                + "      text-align: right;\n"
                + "    }\n"
                + "\n"
                + "    .align-left {\n"
                + "      text-align: left;\n"
                + "    }\n"
                + "\n"
                + "    .clear {\n"
                + "      clear: both;\n"
                + "    }\n"
                + "\n"
                + "    .mt0 {\n"
                + "      margin-top: 0;\n"
                + "    }\n"
                + "\n"
                + "    .mb0 {\n"
                + "      margin-bottom: 0;\n"
                + "    }\n"
                + "\n"
                + "    .preheader {\n"
                + "      color: transparent;\n"
                + "      display: none;\n"
                + "      height: 0;\n"
                + "      max-height: 0;\n"
                + "      max-width: 0;\n"
                + "      opacity: 0;\n"
                + "      overflow: hidden;\n"
                + "      mso-hide: all;\n"
                + "      visibility: hidden;\n"
                + "      width: 0;\n"
                + "    }\n"
                + "\n"
                + "    .powered-by a {\n"
                + "      text-decoration: none;\n"
                + "    }\n"
                + "\n"
                + "    hr {\n"
                + "      border: 0;\n"
                + "      border-bottom: 1px solid #f6f6f6;\n"
                + "      margin: 20px 0;\n"
                + "    }\n"
                + "\n"
                + "    /* -------------------------------------\n"
                + "          RESPONSIVE AND MOBILE FRIENDLY STYLES\n"
                + "      ------------------------------------- */\n"
                + "    @media only screen and (max-width: 620px) {\n"
                + "      table.body h1 {\n"
                + "        font-size: 28px !important;\n"
                + "        margin-bottom: 10px !important;\n"
                + "      }\n"
                + "\n"
                + "      table.body p,\n"
                + "      table.body ul,\n"
                + "      table.body ol,\n"
                + "      table.body td,\n"
                + "      table.body span,\n"
                + "      table.body a {\n"
                + "        font-size: 16px !important;\n"
                + "      }\n"
                + "\n"
                + "      table.body .wrapper,\n"
                + "      table.body .article {\n"
                + "        padding: 10px !important;\n"
                + "      }\n"
                + "\n"
                + "      table.body .content {\n"
                + "        padding: 0 !important;\n"
                + "      }\n"
                + "\n"
                + "      table.body .container {\n"
                + "        padding: 0 !important;\n"
                + "        width: 100% !important;\n"
                + "      }\n"
                + "\n"
                + "      table.body .main {\n"
                + "        border-left-width: 0 !important;\n"
                + "        border-radius: 0 !important;\n"
                + "        border-right-width: 0 !important;\n"
                + "      }\n"
                + "\n"
                + "      table.body .btn table {\n"
                + "        width: 100% !important;\n"
                + "      }\n"
                + "\n"
                + "      table.body .btn a {\n"
                + "        width: 100% !important;\n"
                + "      }\n"
                + "\n"
                + "      table.body .img-responsive {\n"
                + "        height: auto !important;\n"
                + "        max-width: 100% !important;\n"
                + "        width: auto !important;\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    /* -------------------------------------\n"
                + "          PRESERVE THESE STYLES IN THE HEAD\n"
                + "      ------------------------------------- */\n"
                + "    @media all {\n"
                + "      .ExternalClass {\n"
                + "        width: 100%;\n"
                + "      }\n"
                + "\n"
                + "      .ExternalClass,\n"
                + "      .ExternalClass p,\n"
                + "      .ExternalClass span,\n"
                + "      .ExternalClass font,\n"
                + "      .ExternalClass td,\n"
                + "      .ExternalClass div {\n"
                + "        line-height: 100%;\n"
                + "      }\n"
                + "\n"
                + "      .apple-link a {\n"
                + "        color: inherit !important;\n"
                + "        font-family: inherit !important;\n"
                + "        font-size: inherit !important;\n"
                + "        font-weight: inherit !important;\n"
                + "        line-height: inherit !important;\n"
                + "        text-decoration: none !important;\n"
                + "      }\n"
                + "\n"
                + "      #MessageViewBody a {\n"
                + "        color: inherit;\n"
                + "        text-decoration: none;\n"
                + "        font-size: inherit;\n"
                + "        font-family: inherit;\n"
                + "        font-weight: inherit;\n"
                + "        line-height: inherit;\n"
                + "      }\n"
                + "\n"
                + "      .btn-primary table td:hover {\n"
                + "        background-color: #34495e !important;\n"
                + "      }\n"
                + "\n"
                + "      .btn-primary a:hover {\n"
                + "        background-color: #34495e !important;\n"
                + "        border-color: #34495e !important;\n"
                + "      }\n"
                + "    }\n"
                + "  </style>\n"
                + "</head>\n"
                + "\n"
                + "<body>\n"
                + "  <span class=\"preheader\">FUDA Verification Code</span>\n"
                + "  <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"body\">\n"
                + "    <tr>\n"
                + "      <td>&nbsp;</td>\n"
                + "      <td class=\"container\">\n"
                + "        <div class=\"content\">\n"
                + "\n"
                + "          <!-- START CENTERED WHITE CONTAINER -->\n"
                + "          <table role=\"presentation\" class=\"main\">\n"
                + "\n"
                + "            <!-- START MAIN CONTENT AREA -->\n"
                + "            <tr>\n"
                + "              <td class=\"wrapper\">\n"
                + "                <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
                + "                  <tr>\n"
                + "                    <td>\n"
                + "                      <p>Hi " + email + " ! </p>\n"
                + "                      <p>Here's your account launch code.</p>\n"
                + "                      <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"btn btn-succesed\">\n"
                + "                        <tbody>\n"
                + "                          <tr>\n"
                + "                            <td align=\"left\">\n"
                + "                              <table role=\"\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
                + "                                <tbody>\n"
                + "                                  <tr>\n"
                + "                                    <span\n"
                + "                                      style=\"box-sizing:border-box;color:#24292e!important;display:inline-block;background-color:#dedede;border-radius:6px;padding:2px 6px;font:300 48px &quot;SFMono-Regular&quot;,Consolas,&quot;Liberation Mono&quot;,Menlo,monospace\">\n"
                + "                                      " + code + "\n"
                + "                                    </span>\n"
                + "                                  </tr>\n"
                + "                                </tbody>\n"
                + "                              </table>\n"
                + "                            </td>\n"
                + "                          </tr>\n"
                + "                        </tbody>\n"
                + "                      </table>\n"
                + "                      <p>Once completed, you can start using all of FUDA's features to explore, search bus, booking ticket.</p>\n"
                + "                      <p>Good luck! Hope it works.</p>\n"
                + "                    </td>\n"
                + "                  </tr>\n"
                + "                </table>\n"
                + "              </td>\n"
                + "            </tr>\n"
                + "\n"
                + "            <!-- END MAIN CONTENT AREA -->\n"
                + "\n"
                + "\n"
                + "          </table>\n"
                + "          <!-- END CENTERED WHITE CONTAINER -->\n"
                + "\n"
                + "          <!-- START FOOTER -->\n"
                + "          <div class=\"footer\">\n"
                + "            <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
                + "              <tr>\n"
                + "                <td class=\"content-block\">\n"
                + "                  <a><img width=\"520px\" height=\"250px\" src=\"https://i.ibb.co/RbzXDGH/346163504-269689148792233-5682024559632564645-n.png\" alt=\"346163504-269689148792233-5682024559632564645-n\" border=\"0\"></a>\n"
                + "                  <span class=\"apple-link\">Company FUDA Inc, Urban area FPT City, Ngu Hanh Son, Da Nang</span>\n"
                + "                  <br> SUPPORT: <a href=\"https://mail.google.com/mail/u/0/#inbox\">hotrofuda@gmail.com</a>.\n"
                + "                </td>\n"
                + "              </tr>\n"
                + "              <tr>\n"
                + "                <td class=\"content-block powered-by\">\n"
                + "                  Powered by <a href= \"https://www.facebook.com/huygvr\">HUYTRONGLEE</a>.\n"
                + "                </td>\n"
                + "              </tr>\n"
                + "            </table>\n"
                + "          </div>\n"
                + "          <!-- END FOOTER -->\n"
                + "\n"
                + "        </div>\n"
                + "      </td>\n"
                + "      <td>&nbsp;</td>\n"
                + "    </tr>\n"
                + "  </table>\n"
                + "</body>\n"
                + "\n"
                + "</html>";

        Properties props = new Properties();
        props.put("mail.smtp.host", "smtp.gmail.com"); //SMTP Host
        props.put("mail.smtp.port", "587"); //TLS Port
        props.put("mail.smtp.auth", "true"); //enable authentication
        props.put("mail.smtp.starttls.enable", "true"); //enable STARTTLS

        Authenticator auth = new Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(fromEmail, password);
            }
        };
        Session session = Session.getInstance(props, auth);

        MimeMessage msg = new MimeMessage(session);
        //set message headers
        msg.addHeader("Content-type", "text/HTML; charset=UTF-8");
        msg.addHeader("format", "flowed");
        msg.addHeader("Content-Transfer-Encoding", "8bit");

        msg.setFrom(new InternetAddress(fromEmail, "Fuda Support"));

        msg.setReplyTo(InternetAddress.parse(fromEmail, false));

        msg.setSubject(subject, "UTF-8");

        msg.setContent(body, "text/html; charset=utf-8");

        msg.setSentDate(new Date());

        msg.setRecipients(Message.RecipientType.TO, InternetAddress.parse(toEmail, false));
        Transport.send(msg);
        System.out.println("Gui mail thanh cong");
    }

    public void sendCodeChangePassword(String code, String email) throws MessagingException, UnsupportedEncodingException {
        final String fromEmail = "hotrofuda@gmail.com";
        // Mat khai email cua ban
        final String password = "tdnhjwnggkyakjec";
        // dia chi email nguoi nhan
        final String toEmail = email;

        final String subject = "[FUDA Bus Lines] Verify email to change password";
        final String body = "<!doctype html>\n"
                + "<html>\n"
                + "\n"
                + "<head>\n"
                + "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n"
                + "  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n"
                + "  <style>\n"
                + "    img {\n"
                + "      border: none;\n"
                + "      -ms-interpolation-mode: bicubic;\n"
                + "      max-width: 100%;\n"
                + "    }\n"
                + "\n"
                + "    body {\n"
                + "      background-color: #8c8c8c;\n"
                + "      font-family: sans-serif;\n"
                + "      -webkit-font-smoothing: antialiased;\n"
                + "      font-size: 14px;\n"
                + "      line-height: 1.4;\n"
                + "      margin: 0;\n"
                + "      padding: 0;\n"
                + "    }\n"
                + "\n"
                + "    table {\n"
                + "      border-collapse: separate;\n"
                + "      mso-table-lspace: 0pt;\n"
                + "      mso-table-rspace: 0pt;\n"
                + "      width: 100%;\n"
                + "    }\n"
                + "\n"
                + "    table td {\n"
                + "      font-family: sans-serif;\n"
                + "      font-size: 14px;\n"
                + "      vertical-align: top;\n"
                + "    }\n"
                + "\n"
                + "    /* -------------------------------------\n"
                + "          BODY & CONTAINER\n"
                + "      ------------------------------------- */\n"
                + "\n"
                + "    .body {\n"
                + "      background-color: #8c8c8c;\n"
                + "      width: 100%;\n"
                + "    }\n"
                + "\n"
                + "    /* Set a max-width, and make it display as block so it will automatically stretch to that width, but will also shrink down on a phone or something */\n"
                + "    .container {\n"
                + "      display: block;\n"
                + "      margin: 0 auto !important;\n"
                + "      /* makes it centered */\n"
                + "      max-width: 580px;\n"
                + "      padding: 10px;\n"
                + "      width: 580px;\n"
                + "    }\n"
                + "\n"
                + "    /* This should also be a block element, so that it will fill 100% of the .container */\n"
                + "    .content {\n"
                + "      box-sizing: border-box;\n"
                + "      display: block;\n"
                + "      margin: 0 auto;\n"
                + "      max-width: 580px;\n"
                + "      padding: 10px;\n"
                + "    }\n"
                + "\n"
                + "    /* -------------------------------------\n"
                + "          HEADER, FOOTER, MAIN\n"
                + "      ------------------------------------- */\n"
                + "    .main {\n"
                + "      background: #ffffff;\n"
                + "      border-radius: 3px;\n"
                + "      width: 100%;\n"
                + "    }\n"
                + "\n"
                + "    .wrapper {\n"
                + "      box-sizing: border-box;\n"
                + "      padding: 20px;\n"
                + "    }\n"
                + "\n"
                + "    .content-block {\n"
                + "      padding-bottom: 10px;\n"
                + "      padding-top: 10px;\n"
                + "    }\n"
                + "\n"
                + "    .footer {\n"
                + "      clear: both;\n"
                + "      margin-top: 10px;\n"
                + "      text-align: center;\n"
                + "      width: 100%;\n"
                + "    }\n"
                + "\n"
                + "    .footer td,\n"
                + "    .footer p,\n"
                + "    .footer span,\n"
                + "    .footer a {\n"
                + "      color: #ffffff;\n"
                + "      font-size: 12px;\n"
                + "      text-align: center;\n"
                + "    }\n"
                + "\n"
                + "    /* -------------------------------------\n"
                + "          TYPOGRAPHY\n"
                + "      ------------------------------------- */\n"
                + "    h1,\n"
                + "    h2,\n"
                + "    h3,\n"
                + "    h4 {\n"
                + "      color: #000000;\n"
                + "      font-family: sans-serif;\n"
                + "      font-weight: 400;\n"
                + "      line-height: 1.4;\n"
                + "      margin: 0;\n"
                + "      margin-bottom: 30px;\n"
                + "    }\n"
                + "\n"
                + "    h1 {\n"
                + "      font-size: 35px;\n"
                + "      font-weight: 300;\n"
                + "      text-align: center;\n"
                + "      text-transform: capitalize;\n"
                + "    }\n"
                + "\n"
                + "    p,\n"
                + "    ul,\n"
                + "    ol {\n"
                + "      font-family: sans-serif;\n"
                + "      font-size: 14px;\n"
                + "      font-weight: normal;\n"
                + "      margin: 0;\n"
                + "      margin-bottom: 15px;\n"
                + "    }\n"
                + "\n"
                + "    p li,\n"
                + "    ul li,\n"
                + "    ol li {\n"
                + "      list-style-position: inside;\n"
                + "      margin-left: 5px;\n"
                + "    }\n"
                + "\n"
                + "    a {\n"
                + "      color: #3498db;\n"
                + "      text-decoration: underline;\n"
                + "    }\n"
                + "\n"
                + "    /* -------------------------------------\n"
                + "          BUTTONS\n"
                + "      ------------------------------------- */\n"
                + "    .btn {\n"
                + "      box-sizing: border-box;\n"
                + "      width: 100%;\n"
                + "    }\n"
                + "\n"
                + "    .btn>tbody>tr>td {\n"
                + "      padding-bottom: 15px;\n"
                + "    }\n"
                + "\n"
                + "    .btn table {\n"
                + "      width: auto;\n"
                + "    }\n"
                + "\n"
                + "    .btn table td {\n"
                + "      background-color: #ffffff;\n"
                + "      border-radius: 5px;\n"
                + "      text-align: center;\n"
                + "    }\n"
                + "\n"
                + "    .btn a {\n"
                + "      background-color: #ffffff;\n"
                + "      border: solid 1px #3498db;\n"
                + "      border-radius: 5px;\n"
                + "      box-sizing: border-box;\n"
                + "      color: #3498db;\n"
                + "      cursor: pointer;\n"
                + "      display: inline-block;\n"
                + "      font-size: 14px;\n"
                + "      font-weight: bold;\n"
                + "      margin: 0;\n"
                + "      padding: 12px 25px;\n"
                + "      text-decoration: none;\n"
                + "      text-transform: capitalize;\n"
                + "    }\n"
                + "\n"
                + "    .btn-primary table td {\n"
                + "      background-color: #3498db;\n"
                + "    }\n"
                + "\n"
                + "    .btn-primary a {\n"
                + "      background-color: #3498db;\n"
                + "      border-color: #3498db;\n"
                + "      color: #ffffff;\n"
                + "    }\n"
                + "\n"
                + "    /* -------------------------------------\n"
                + "          OTHER STYLES THAT MIGHT BE USEFUL\n"
                + "      ------------------------------------- */\n"
                + "    .last {\n"
                + "      margin-bottom: 0;\n"
                + "    }\n"
                + "\n"
                + "    .first {\n"
                + "      margin-top: 0;\n"
                + "    }\n"
                + "\n"
                + "    .align-center {\n"
                + "      text-align: center;\n"
                + "    }\n"
                + "\n"
                + "    .align-right {\n"
                + "      text-align: right;\n"
                + "    }\n"
                + "\n"
                + "    .align-left {\n"
                + "      text-align: left;\n"
                + "    }\n"
                + "\n"
                + "    .clear {\n"
                + "      clear: both;\n"
                + "    }\n"
                + "\n"
                + "    .mt0 {\n"
                + "      margin-top: 0;\n"
                + "    }\n"
                + "\n"
                + "    .mb0 {\n"
                + "      margin-bottom: 0;\n"
                + "    }\n"
                + "\n"
                + "    .preheader {\n"
                + "      color: transparent;\n"
                + "      display: none;\n"
                + "      height: 0;\n"
                + "      max-height: 0;\n"
                + "      max-width: 0;\n"
                + "      opacity: 0;\n"
                + "      overflow: hidden;\n"
                + "      mso-hide: all;\n"
                + "      visibility: hidden;\n"
                + "      width: 0;\n"
                + "    }\n"
                + "\n"
                + "    .powered-by a {\n"
                + "      text-decoration: none;\n"
                + "    }\n"
                + "\n"
                + "    hr {\n"
                + "      border: 0;\n"
                + "      border-bottom: 1px solid #f6f6f6;\n"
                + "      margin: 20px 0;\n"
                + "    }\n"
                + "\n"
                + "    /* -------------------------------------\n"
                + "          RESPONSIVE AND MOBILE FRIENDLY STYLES\n"
                + "      ------------------------------------- */\n"
                + "    @media only screen and (max-width: 620px) {\n"
                + "      table.body h1 {\n"
                + "        font-size: 28px !important;\n"
                + "        margin-bottom: 10px !important;\n"
                + "      }\n"
                + "\n"
                + "      table.body p,\n"
                + "      table.body ul,\n"
                + "      table.body ol,\n"
                + "      table.body td,\n"
                + "      table.body span,\n"
                + "      table.body a {\n"
                + "        font-size: 16px !important;\n"
                + "      }\n"
                + "\n"
                + "      table.body .wrapper,\n"
                + "      table.body .article {\n"
                + "        padding: 10px !important;\n"
                + "      }\n"
                + "\n"
                + "      table.body .content {\n"
                + "        padding: 0 !important;\n"
                + "      }\n"
                + "\n"
                + "      table.body .container {\n"
                + "        padding: 0 !important;\n"
                + "        width: 100% !important;\n"
                + "      }\n"
                + "\n"
                + "      table.body .main {\n"
                + "        border-left-width: 0 !important;\n"
                + "        border-radius: 0 !important;\n"
                + "        border-right-width: 0 !important;\n"
                + "      }\n"
                + "\n"
                + "      table.body .btn table {\n"
                + "        width: 100% !important;\n"
                + "      }\n"
                + "\n"
                + "      table.body .btn a {\n"
                + "        width: 100% !important;\n"
                + "      }\n"
                + "\n"
                + "      table.body .img-responsive {\n"
                + "        height: auto !important;\n"
                + "        max-width: 100% !important;\n"
                + "        width: auto !important;\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    /* -------------------------------------\n"
                + "          PRESERVE THESE STYLES IN THE HEAD\n"
                + "      ------------------------------------- */\n"
                + "    @media all {\n"
                + "      .ExternalClass {\n"
                + "        width: 100%;\n"
                + "      }\n"
                + "\n"
                + "      .ExternalClass,\n"
                + "      .ExternalClass p,\n"
                + "      .ExternalClass span,\n"
                + "      .ExternalClass font,\n"
                + "      .ExternalClass td,\n"
                + "      .ExternalClass div {\n"
                + "        line-height: 100%;\n"
                + "      }\n"
                + "\n"
                + "      .apple-link a {\n"
                + "        color: inherit !important;\n"
                + "        font-family: inherit !important;\n"
                + "        font-size: inherit !important;\n"
                + "        font-weight: inherit !important;\n"
                + "        line-height: inherit !important;\n"
                + "        text-decoration: none !important;\n"
                + "      }\n"
                + "\n"
                + "      #MessageViewBody a {\n"
                + "        color: inherit;\n"
                + "        text-decoration: none;\n"
                + "        font-size: inherit;\n"
                + "        font-family: inherit;\n"
                + "        font-weight: inherit;\n"
                + "        line-height: inherit;\n"
                + "      }\n"
                + "\n"
                + "      .btn-primary table td:hover {\n"
                + "        background-color: #34495e !important;\n"
                + "      }\n"
                + "\n"
                + "      .btn-primary a:hover {\n"
                + "        background-color: #34495e !important;\n"
                + "        border-color: #34495e !important;\n"
                + "      }\n"
                + "    }\n"
                + "  </style>\n"
                + "</head>\n"
                + "\n"
                + "<body>\n"
                + "  <span class=\"preheader\">FUDA Verification Code</span>\n"
                + "  <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"body\">\n"
                + "    <tr>\n"
                + "      <td>&nbsp;</td>\n"
                + "      <td class=\"container\">\n"
                + "        <div class=\"content\">\n"
                + "\n"
                + "          <!-- START CENTERED WHITE CONTAINER -->\n"
                + "          <table role=\"presentation\" class=\"main\">\n"
                + "\n"
                + "            <!-- START MAIN CONTENT AREA -->\n"
                + "            <tr>\n"
                + "              <td class=\"wrapper\">\n"
                + "                <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
                + "                  <tr>\n"
                + "                    <td>\n"
                + "                      <p>Hi " + email + " ! </p>\n"
                + "                      <p>Here's your account launch code.</p>\n"
                + "                      <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"btn btn-succesed\">\n"
                + "                        <tbody>\n"
                + "                          <tr>\n"
                + "                            <td align=\"left\">\n"
                + "                              <table role=\"\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
                + "                                <tbody>\n"
                + "                                  <tr>\n"
                + "                                    <span\n"
                + "                                      style=\"box-sizing:border-box;color:#24292e!important;display:inline-block;background-color:#dedede;border-radius:6px;padding:2px 6px;font:300 48px &quot;SFMono-Regular&quot;,Consolas,&quot;Liberation Mono&quot;,Menlo,monospace\">\n"
                + "                                      " + code + "\n"
                + "                                    </span>\n"
                + "                                  </tr>\n"
                + "                                </tbody>\n"
                + "                              </table>\n"
                + "                            </td>\n"
                + "                          </tr>\n"
                + "                        </tbody>\n"
                + "                      </table>\n"
                + "                      <p>Once completed, you can start using all of FUDA's features to explore, search bus, booking ticket.</p>\n"
                + "                      <p>Good luck! Hope it works.</p>\n"
                + "                    </td>\n"
                + "                  </tr>\n"
                + "                </table>\n"
                + "              </td>\n"
                + "            </tr>\n"
                + "\n"
                + "            <!-- END MAIN CONTENT AREA -->\n"
                + "\n"
                + "\n"
                + "          </table>\n"
                + "          <!-- END CENTERED WHITE CONTAINER -->\n"
                + "\n"
                + "          <!-- START FOOTER -->\n"
                + "          <div class=\"footer\">\n"
                + "            <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
                + "              <tr>\n"
                + "                <td class=\"content-block\">\n"
                + "                  <a><img width=\"520px\" height=\"250px\" src=\"https://i.ibb.co/RbzXDGH/346163504-269689148792233-5682024559632564645-n.png\" alt=\"346163504-269689148792233-5682024559632564645-n\" border=\"0\"></a>\n"
                + "                  <span class=\"apple-link\">Company FUDA Inc, Urban area FPT City, Ngu Hanh Son, Da Nang</span>\n"
                + "                  <br> SUPPORT: <a href=\"https://mail.google.com/mail/u/0/#inbox\">hotrofuda@gmail.com</a>.\n"
                + "                </td>\n"
                + "              </tr>\n"
                + "              <tr>\n"
                + "                <td class=\"content-block powered-by\">\n"
                + "                  Powered by <a href= \"https://www.facebook.com/huygvr\">HUYTRONGLEE</a>.\n"
                + "                </td>\n"
                + "              </tr>\n"
                + "            </table>\n"
                + "          </div>\n"
                + "          <!-- END FOOTER -->\n"
                + "\n"
                + "        </div>\n"
                + "      </td>\n"
                + "      <td>&nbsp;</td>\n"
                + "    </tr>\n"
                + "  </table>\n"
                + "</body>\n"
                + "\n"
                + "</html>";

        Properties props = new Properties();
        props.put("mail.smtp.host", "smtp.gmail.com"); //SMTP Host
        props.put("mail.smtp.port", "587"); //TLS Port
        props.put("mail.smtp.auth", "true"); //enable authentication
        props.put("mail.smtp.starttls.enable", "true"); //enable STARTTLS

        Authenticator auth = new Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(fromEmail, password);
            }
        };
        Session session = Session.getInstance(props, auth);

        MimeMessage msg = new MimeMessage(session);
        //set message headers
        msg.addHeader("Content-type", "text/HTML; charset=UTF-8");
        msg.addHeader("format", "flowed");
        msg.addHeader("Content-Transfer-Encoding", "8bit");

        msg.setFrom(new InternetAddress(fromEmail, "Fuda Support"));

        msg.setReplyTo(InternetAddress.parse(fromEmail, false));

        msg.setSubject(subject, "UTF-8");

        msg.setContent(body, "text/html; charset=utf-8");

        msg.setSentDate(new Date());

        msg.setRecipients(Message.RecipientType.TO, InternetAddress.parse(toEmail, false));
        Transport.send(msg);
        System.out.println("Gui mail thanh cong");
    }
    public void sendPasswordToCustomer(String passwordCustomer, String email) throws MessagingException, UnsupportedEncodingException {
        final String fromEmail = "hotrofuda@gmail.com";
        // Mat khai email cua ban
        final String password = "tdnhjwnggkyakjec";
        // dia chi email nguoi nhan
        final String toEmail = email;

        final String subject = "[FUDA Bus Lines] Do not share to Anyone !!!";
        final String body = "<!doctype html>\n"
                + "<html>\n"
                + "\n"
                + "<head>\n"
                + "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n"
                + "  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n"
                + "  <style>\n"
                + "    img {\n"
                + "      border: none;\n"
                + "      -ms-interpolation-mode: bicubic;\n"
                + "      max-width: 100%;\n"
                + "    }\n"
                + "\n"
                + "    body {\n"
                + "      background-color: #8c8c8c;\n"
                + "      font-family: sans-serif;\n"
                + "      -webkit-font-smoothing: antialiased;\n"
                + "      font-size: 14px;\n"
                + "      line-height: 1.4;\n"
                + "      margin: 0;\n"
                + "      padding: 0;\n"
                + "    }\n"
                + "\n"
                + "    table {\n"
                + "      border-collapse: separate;\n"
                + "      mso-table-lspace: 0pt;\n"
                + "      mso-table-rspace: 0pt;\n"
                + "      width: 100%;\n"
                + "    }\n"
                + "\n"
                + "    table td {\n"
                + "      font-family: sans-serif;\n"
                + "      font-size: 14px;\n"
                + "      vertical-align: top;\n"
                + "    }\n"
                + "\n"
                + "    /* -------------------------------------\n"
                + "          BODY & CONTAINER\n"
                + "      ------------------------------------- */\n"
                + "\n"
                + "    .body {\n"
                + "      background-color: #8c8c8c;\n"
                + "      width: 100%;\n"
                + "    }\n"
                + "\n"
                + "    /* Set a max-width, and make it display as block so it will automatically stretch to that width, but will also shrink down on a phone or something */\n"
                + "    .container {\n"
                + "      display: block;\n"
                + "      margin: 0 auto !important;\n"
                + "      /* makes it centered */\n"
                + "      max-width: 580px;\n"
                + "      padding: 10px;\n"
                + "      width: 580px;\n"
                + "    }\n"
                + "\n"
                + "    /* This should also be a block element, so that it will fill 100% of the .container */\n"
                + "    .content {\n"
                + "      box-sizing: border-box;\n"
                + "      display: block;\n"
                + "      margin: 0 auto;\n"
                + "      max-width: 580px;\n"
                + "      padding: 10px;\n"
                + "    }\n"
                + "\n"
                + "    /* -------------------------------------\n"
                + "          HEADER, FOOTER, MAIN\n"
                + "      ------------------------------------- */\n"
                + "    .main {\n"
                + "      background: #ffffff;\n"
                + "      border-radius: 3px;\n"
                + "      width: 100%;\n"
                + "    }\n"
                + "\n"
                + "    .wrapper {\n"
                + "      box-sizing: border-box;\n"
                + "      padding: 20px;\n"
                + "    }\n"
                + "\n"
                + "    .content-block {\n"
                + "      padding-bottom: 10px;\n"
                + "      padding-top: 10px;\n"
                + "    }\n"
                + "\n"
                + "    .footer {\n"
                + "      clear: both;\n"
                + "      margin-top: 10px;\n"
                + "      text-align: center;\n"
                + "      width: 100%;\n"
                + "    }\n"
                + "\n"
                + "    .footer td,\n"
                + "    .footer p,\n"
                + "    .footer span,\n"
                + "    .footer a {\n"
                + "      color: #ffffff;\n"
                + "      font-size: 12px;\n"
                + "      text-align: center;\n"
                + "    }\n"
                + "\n"
                + "    /* -------------------------------------\n"
                + "          TYPOGRAPHY\n"
                + "      ------------------------------------- */\n"
                + "    h1,\n"
                + "    h2,\n"
                + "    h3,\n"
                + "    h4 {\n"
                + "      color: #000000;\n"
                + "      font-family: sans-serif;\n"
                + "      font-weight: 400;\n"
                + "      line-height: 1.4;\n"
                + "      margin: 0;\n"
                + "      margin-bottom: 30px;\n"
                + "    }\n"
                + "\n"
                + "    h1 {\n"
                + "      font-size: 35px;\n"
                + "      font-weight: 300;\n"
                + "      text-align: center;\n"
                + "      text-transform: capitalize;\n"
                + "    }\n"
                + "\n"
                + "    p,\n"
                + "    ul,\n"
                + "    ol {\n"
                + "      font-family: sans-serif;\n"
                + "      font-size: 14px;\n"
                + "      font-weight: normal;\n"
                + "      margin: 0;\n"
                + "      margin-bottom: 15px;\n"
                + "    }\n"
                + "\n"
                + "    p li,\n"
                + "    ul li,\n"
                + "    ol li {\n"
                + "      list-style-position: inside;\n"
                + "      margin-left: 5px;\n"
                + "    }\n"
                + "\n"
                + "    a {\n"
                + "      color: #3498db;\n"
                + "      text-decoration: underline;\n"
                + "    }\n"
                + "\n"
                + "    /* -------------------------------------\n"
                + "          BUTTONS\n"
                + "      ------------------------------------- */\n"
                + "    .btn {\n"
                + "      box-sizing: border-box;\n"
                + "      width: 100%;\n"
                + "    }\n"
                + "\n"
                + "    .btn>tbody>tr>td {\n"
                + "      padding-bottom: 15px;\n"
                + "    }\n"
                + "\n"
                + "    .btn table {\n"
                + "      width: auto;\n"
                + "    }\n"
                + "\n"
                + "    .btn table td {\n"
                + "      background-color: #ffffff;\n"
                + "      border-radius: 5px;\n"
                + "      text-align: center;\n"
                + "    }\n"
                + "\n"
                + "    .btn a {\n"
                + "      background-color: #ffffff;\n"
                + "      border: solid 1px #3498db;\n"
                + "      border-radius: 5px;\n"
                + "      box-sizing: border-box;\n"
                + "      color: #3498db;\n"
                + "      cursor: pointer;\n"
                + "      display: inline-block;\n"
                + "      font-size: 14px;\n"
                + "      font-weight: bold;\n"
                + "      margin: 0;\n"
                + "      padding: 12px 25px;\n"
                + "      text-decoration: none;\n"
                + "      text-transform: capitalize;\n"
                + "    }\n"
                + "\n"
                + "    .btn-primary table td {\n"
                + "      background-color: #3498db;\n"
                + "    }\n"
                + "\n"
                + "    .btn-primary a {\n"
                + "      background-color: #3498db;\n"
                + "      border-color: #3498db;\n"
                + "      color: #ffffff;\n"
                + "    }\n"
                + "\n"
                + "    /* -------------------------------------\n"
                + "          OTHER STYLES THAT MIGHT BE USEFUL\n"
                + "      ------------------------------------- */\n"
                + "    .last {\n"
                + "      margin-bottom: 0;\n"
                + "    }\n"
                + "\n"
                + "    .first {\n"
                + "      margin-top: 0;\n"
                + "    }\n"
                + "\n"
                + "    .align-center {\n"
                + "      text-align: center;\n"
                + "    }\n"
                + "\n"
                + "    .align-right {\n"
                + "      text-align: right;\n"
                + "    }\n"
                + "\n"
                + "    .align-left {\n"
                + "      text-align: left;\n"
                + "    }\n"
                + "\n"
                + "    .clear {\n"
                + "      clear: both;\n"
                + "    }\n"
                + "\n"
                + "    .mt0 {\n"
                + "      margin-top: 0;\n"
                + "    }\n"
                + "\n"
                + "    .mb0 {\n"
                + "      margin-bottom: 0;\n"
                + "    }\n"
                + "\n"
                + "    .preheader {\n"
                + "      color: transparent;\n"
                + "      display: none;\n"
                + "      height: 0;\n"
                + "      max-height: 0;\n"
                + "      max-width: 0;\n"
                + "      opacity: 0;\n"
                + "      overflow: hidden;\n"
                + "      mso-hide: all;\n"
                + "      visibility: hidden;\n"
                + "      width: 0;\n"
                + "    }\n"
                + "\n"
                + "    .powered-by a {\n"
                + "      text-decoration: none;\n"
                + "    }\n"
                + "\n"
                + "    hr {\n"
                + "      border: 0;\n"
                + "      border-bottom: 1px solid #f6f6f6;\n"
                + "      margin: 20px 0;\n"
                + "    }\n"
                + "\n"
                + "    /* -------------------------------------\n"
                + "          RESPONSIVE AND MOBILE FRIENDLY STYLES\n"
                + "      ------------------------------------- */\n"
                + "    @media only screen and (max-width: 620px) {\n"
                + "      table.body h1 {\n"
                + "        font-size: 28px !important;\n"
                + "        margin-bottom: 10px !important;\n"
                + "      }\n"
                + "\n"
                + "      table.body p,\n"
                + "      table.body ul,\n"
                + "      table.body ol,\n"
                + "      table.body td,\n"
                + "      table.body span,\n"
                + "      table.body a {\n"
                + "        font-size: 16px !important;\n"
                + "      }\n"
                + "\n"
                + "      table.body .wrapper,\n"
                + "      table.body .article {\n"
                + "        padding: 10px !important;\n"
                + "      }\n"
                + "\n"
                + "      table.body .content {\n"
                + "        padding: 0 !important;\n"
                + "      }\n"
                + "\n"
                + "      table.body .container {\n"
                + "        padding: 0 !important;\n"
                + "        width: 100% !important;\n"
                + "      }\n"
                + "\n"
                + "      table.body .main {\n"
                + "        border-left-width: 0 !important;\n"
                + "        border-radius: 0 !important;\n"
                + "        border-right-width: 0 !important;\n"
                + "      }\n"
                + "\n"
                + "      table.body .btn table {\n"
                + "        width: 100% !important;\n"
                + "      }\n"
                + "\n"
                + "      table.body .btn a {\n"
                + "        width: 100% !important;\n"
                + "      }\n"
                + "\n"
                + "      table.body .img-responsive {\n"
                + "        height: auto !important;\n"
                + "        max-width: 100% !important;\n"
                + "        width: auto !important;\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    /* -------------------------------------\n"
                + "          PRESERVE THESE STYLES IN THE HEAD\n"
                + "      ------------------------------------- */\n"
                + "    @media all {\n"
                + "      .ExternalClass {\n"
                + "        width: 100%;\n"
                + "      }\n"
                + "\n"
                + "      .ExternalClass,\n"
                + "      .ExternalClass p,\n"
                + "      .ExternalClass span,\n"
                + "      .ExternalClass font,\n"
                + "      .ExternalClass td,\n"
                + "      .ExternalClass div {\n"
                + "        line-height: 100%;\n"
                + "      }\n"
                + "\n"
                + "      .apple-link a {\n"
                + "        color: inherit !important;\n"
                + "        font-family: inherit !important;\n"
                + "        font-size: inherit !important;\n"
                + "        font-weight: inherit !important;\n"
                + "        line-height: inherit !important;\n"
                + "        text-decoration: none !important;\n"
                + "      }\n"
                + "\n"
                + "      #MessageViewBody a {\n"
                + "        color: inherit;\n"
                + "        text-decoration: none;\n"
                + "        font-size: inherit;\n"
                + "        font-family: inherit;\n"
                + "        font-weight: inherit;\n"
                + "        line-height: inherit;\n"
                + "      }\n"
                + "\n"
                + "      .btn-primary table td:hover {\n"
                + "        background-color: #34495e !important;\n"
                + "      }\n"
                + "\n"
                + "      .btn-primary a:hover {\n"
                + "        background-color: #34495e !important;\n"
                + "        border-color: #34495e !important;\n"
                + "      }\n"
                + "    }\n"
                + "  </style>\n"
                + "</head>\n"
                + "\n"
                + "<body>\n"
                + "  <span class=\"preheader\">FUDA Your Password</span>\n"
                + "  <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"body\">\n"
                + "    <tr>\n"
                + "      <td>&nbsp;</td>\n"
                + "      <td class=\"container\">\n"
                + "        <div class=\"content\">\n"
                + "\n"
                + "          <!-- START CENTERED WHITE CONTAINER -->\n"
                + "          <table role=\"presentation\" class=\"main\">\n"
                + "\n"
                + "            <!-- START MAIN CONTENT AREA -->\n"
                + "            <tr>\n"
                + "              <td class=\"wrapper\">\n"
                + "                <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
                + "                  <tr>\n"
                + "                    <td>\n"
                + "                      <p>Hi " + email + " ! </p>\n"
                + "                      <p>Here's your password, do not share to anyone !</p>\n"
                + "                      <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"btn btn-succesed\">\n"
                + "                        <tbody>\n"
                + "                          <tr>\n"
                + "                            <td align=\"left\">\n"
                + "                              <table role=\"\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
                + "                                <tbody>\n"
                + "                                  <tr>\n"
                + "                                    <span\n"
                + "                                      style=\"box-sizing:border-box;color:#24292e!important;display:inline-block;background-color:#dedede;border-radius:6px;padding:2px 6px;font:300 48px &quot;SFMono-Regular&quot;,Consolas,&quot;Liberation Mono&quot;,Menlo,monospace\">\n"
                + "                                      " + passwordCustomer + "\n"
                + "                                    </span>\n"
                + "                                  </tr>\n"
                + "                                </tbody>\n"
                + "                              </table>\n"
                + "                            </td>\n"
                + "                          </tr>\n"
                + "                        </tbody>\n"
                + "                      </table>\n"
                + "                      <p>Once completed, you can start using all of FUDA's features to explore, search bus, booking ticket.</p>\n"
                + "                      <p>Good luck! Hope it works.</p>\n"
                + "                    </td>\n"
                + "                  </tr>\n"
                + "                </table>\n"
                + "              </td>\n"
                + "            </tr>\n"
                + "\n"
                + "            <!-- END MAIN CONTENT AREA -->\n"
                + "\n"
                + "\n"
                + "          </table>\n"
                + "          <!-- END CENTERED WHITE CONTAINER -->\n"
                + "\n"
                + "          <!-- START FOOTER -->\n"
                + "          <div class=\"footer\">\n"
                + "            <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
                + "              <tr>\n"
                + "                <td class=\"content-block\">\n"
                + "                  <a><img width=\"520px\" height=\"250px\" src=\"https://i.ibb.co/RbzXDGH/346163504-269689148792233-5682024559632564645-n.png\" alt=\"346163504-269689148792233-5682024559632564645-n\" border=\"0\"></a>\n"
                + "                  <span class=\"apple-link\">Company FUDA Inc, Urban area FPT City, Ngu Hanh Son, Da Nang</span>\n"
                + "                  <br> SUPPORT: <a href=\"https://mail.google.com/mail/u/0/#inbox\">hotrofuda@gmail.com</a>.\n"
                + "                </td>\n"
                + "              </tr>\n"
                + "              <tr>\n"
                + "                <td class=\"content-block powered-by\">\n"
                + "                  Powered by <a href= \"https://www.facebook.com/huygvr\">HUYTRONGLEE</a>.\n"
                + "                </td>\n"
                + "              </tr>\n"
                + "            </table>\n"
                + "          </div>\n"
                + "          <!-- END FOOTER -->\n"
                + "\n"
                + "        </div>\n"
                + "      </td>\n"
                + "      <td>&nbsp;</td>\n"
                + "    </tr>\n"
                + "  </table>\n"
                + "</body>\n"
                + "\n"
                + "</html>";

        Properties props = new Properties();
        props.put("mail.smtp.host", "smtp.gmail.com"); //SMTP Host
        props.put("mail.smtp.port", "587"); //TLS Port
        props.put("mail.smtp.auth", "true"); //enable authentication
        props.put("mail.smtp.starttls.enable", "true"); //enable STARTTLS

        Authenticator auth = new Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(fromEmail, password);
            }
        };
        Session session = Session.getInstance(props, auth);

        MimeMessage msg = new MimeMessage(session);
        //set message headers
        msg.addHeader("Content-type", "text/HTML; charset=UTF-8");
        msg.addHeader("format", "flowed");
        msg.addHeader("Content-Transfer-Encoding", "8bit");

        msg.setFrom(new InternetAddress(fromEmail, "Fuda Support"));

        msg.setReplyTo(InternetAddress.parse(fromEmail, false));

        msg.setSubject(subject, "UTF-8");

        msg.setContent(body, "text/html; charset=utf-8");

        msg.setSentDate(new Date());

        msg.setRecipients(Message.RecipientType.TO, InternetAddress.parse(toEmail, false));
        Transport.send(msg);
        System.out.println("Gui mail thanh cong");
    }
}
